# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'deployVmConnection'
    subscriptionId: '0f74540b-1fa3-440a-b624-8f448a34650a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myResourceGroup'
    location: 'Korea Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/insang1983/cloudtest/main/deployvm/azuredeploy.json'
    deploymentMode: 'Incremental'
